# ┌──────────────────────────────────────────────────────────────┐
# |			 Default Programs			 |
# └──────────────────────────────────────────────────────────────┘

$terminal    = kitty
$fileManager = nautilus
$browser     = vivaldi
$editor      = nvim
$menu        = rofi -show drun -theme ~/.config/rofi/prism.rasi
$launcher    = rofi -show combi -theme ~/.config/rofi/prism.rasi
$lockdaemon  = hyprlock
$powermenu   = wlogout -b 5 -c 10 -r 10 -m 5 --layout ~/.config/wlogout/layout --css ~/.config/wlogout/style.css
