# ┌──────────────────────────────────────────────────────────────┐
# |                          hypridle                            |
# |  Locks the screen with hyprlock after 5 minutes of inactivity |
# └──────────────────────────────────────────────────────────────┘

general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances
    before_sleep_cmd = loginctl lock-session    # lock before suspend too
}

listener {
    timeout = 300                       # 5 minutes
    on-timeout = loginctl lock-session  # lock screen when timeout has passed
}
