source = ~/.config/hypr/conf/colors.conf

general {
    disable_loading_bar = true
    hide_cursor = true
    grace = 0
    no_fade_in = false
}

background {
    monitor =
    path = ~/bin/dotfiles/wallpapers/prism-default.png
    blur_passes = 3
    blur_size = 8
    contrast = 0.9
    brightness = 0.7
    vibrancy = 0.4
    color = $background
}

input-field {
    monitor =
    size = 260, 60
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.25
    outer_color = $primary
    inner_color = $surface_container
    font_color = $on_surface
    fade_on_empty = true
    placeholder_text = <span foreground="##cac4d0">Password...</span>
    hide_input = false
    position = 0, -140
    halign = center
    valign = center
    rounding = 30
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = $on_background
    font_size = 90
    font_family = Product Sans
    position = 0, 160
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] echo "$(date +"%A, %d %B")"
    color = $on_surface_variant
    font_size = 22
    font_family = Product Sans
    position = 0, 60
    halign = center
    valign = center
}

label {
    monitor =
    text = $USER
    color = $on_background
    font_size = 18
    font_family = Product Sans
    position = 0, -70
    halign = center
    valign = center
}
