-- ┌──────────────────────────────────────────────────────────────┐
-- |                  Material You Color Palette                  |
-- └──────────────────────────────────────────────────────────────┘
-- Ported from colors.conf. Full palette kept for parity even though
-- only a few keys are referenced directly by looks.lua today.

return {
    image                        = "/home/fstorfa/bin/dotfiles/quickshell/ii/assets/images/default_wallpaper.png",
    background                   = "rgba(fff7fbff)",
    error                        = "rgba(ba1a1aff)",
    error_container              = "rgba(ffdad6ff)",
    inverse_on_surface           = "rgba(f8eef5ff)",
    inverse_primary              = "rgba(e4b7f3ff)",
    inverse_surface              = "rgba(342f34ff)",
    on_background                = "rgba(1f1a1fff)",
    on_error                     = "rgba(ffffffff)",
    on_error_container           = "rgba(410002ff)",
    on_primary                   = "rgba(ffffffff)",
    on_primary_container         = "rgba(2d0a3dff)",
    on_primary_fixed             = "rgba(2d0a3dff)",
    on_primary_fixed_variant     = "rgba(5d386bff)",
    on_secondary                 = "rgba(ffffffff)",
    on_secondary_container       = "rgba(231728ff)",
    on_secondary_fixed           = "rgba(231728ff)",
    on_secondary_fixed_variant   = "rgba(504255ff)",
    on_surface                   = "rgba(1f1a1fff)",
    on_surface_variant           = "rgba(4c444dff)",
    on_tertiary                  = "rgba(ffffffff)",
    on_tertiary_container        = "rgba(331111ff)",
    on_tertiary_fixed            = "rgba(331111ff)",
    on_tertiary_fixed_variant    = "rgba(663b39ff)",
    outline                      = "rgba(7d747dff)",
    outline_variant              = "rgba(cec3cdff)",
    primary                      = "rgba(765085ff)",
    primary_container            = "rgba(f8d8ffff)",
    primary_fixed                = "rgba(f8d8ffff)",
    primary_fixed_dim            = "rgba(e4b7f3ff)",
    scrim                        = "rgba(000000ff)",
    secondary                    = "rgba(69596dff)",
    secondary_container          = "rgba(f1dcf4ff)",
    secondary_fixed              = "rgba(f1dcf4ff)",
    secondary_fixed_dim          = "rgba(d4c0d7ff)",
    shadow                       = "rgba(000000ff)",
    source_color                 = "rgba(4a3c4eff)",
    surface                      = "rgba(fff7fbff)",
    surface_bright               = "rgba(fff7fbff)",
    surface_container            = "rgba(f5ebf3ff)",
    surface_container_high       = "rgba(efe5edff)",
    surface_container_highest    = "rgba(e9e0e7ff)",
    surface_container_low        = "rgba(fbf1f8ff)",
    surface_container_lowest     = "rgba(ffffffff)",
    surface_dim                  = "rgba(e1d7dfff)",
    surface_tint                 = "rgba(765085ff)",
    surface_variant              = "rgba(ebdfe9ff)",
    tertiary                     = "rgba(815250ff)",
    tertiary_container           = "rgba(ffdad8ff)",
    tertiary_fixed               = "rgba(ffdad8ff)",
    tertiary_fixed_dim           = "rgba(f5b7b5ff)",
}
